#!/usr/bin/env bash
set -e # halt script on error
jekyll --version

git config --global user.email "travis@ci.org"
git config --global user.name "Travis CI"

bundle exec jekyll build --trace
bundle exec htmlproofer ./_site --disable-external --trace
